
defaultMarkdownHandler = "goldmark" # blackfriday or goldmark
[goldmark]
[goldmark.renderer]
unsafe = true
[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
noHl = false
style = 'onedark' # https://xyproto.github.io/splash/docs/all.html
tabWidth = 4
